### ISSUE TITLE
Glyphs Set

### ISSUE THREAD

**Issue by resindrake** [FeignedIgnorance/StickyMC-Resource-Pack#10]
- [x] Glyphs Chisel
- [x] Glyphs Chopper
- [ ] Glyphs Cleaver
- [ ] Glyphs Fishing Rod
- [x] Glyphs Recurve
- [ ] Glyphs Spade

**Comment by FeignedIgnorance** [comment]
We're gonna need to find a way to simplify the hell out of these textures.

**Comment by resindrake** [comment]
Let me have a crack at it later.

Obviously the intricacies of the weapons will be completely lost to the pixel art. But we can keep the black and orange handles, and blue transparent toolheads and it'll convey the point clearly enough, without any intricate patterns.

**Comment by resindrake** [comment]
Spent ages trying to get these BotW textures implemented but it just wasn't feasible. Even when making the texture super dead simple, the colours just refused to work.

I've gone with a completely different design for the glyphs sets that I think you'll appreciate. The flame texture might be a tad too flashy for the Glyphs set though, dunno. In any case it's just a sketch to demonstrate the concept; the fire animation would need some cleaning up.

![glyphs_chisel](https://user-images.githubusercontent.com/62374268/100489123-915abc00-3166-11eb-9a35-ab9c2830ff12.gif)
![glyphs_chopper](https://user-images.githubusercontent.com/62374268/100489125-928be900-3166-11eb-8054-ad2584c0a54b.gif)

**Comment by resindrake** [comment]
Working demonstration can be found as of 2fa3624

**Comment by resindrake** [comment]
My attempt at the Glyphs Recurve as of c4c163f. No way I was adding animated fire for all the states it could be in, so I went with the simpler approach.

![glyphs_recurve](https://user-images.githubusercontent.com/62374268/100498772-c09a1900-31b8-11eb-9f19-aab1ba5e7a59.gif)

**Comment by resindrake** [comment]
@FeignedIgnorance Give me the greenlight on these if you're happy with the overall aesthetic and I'll implement the rest of the tools! If the animated fire is too much, I can simplify it to a static texture that's more like a subtle glow.

**Comment by FeignedIgnorance** [comment]
I do think the fire is a bit overbearing. Is it possible you could make the set palette fit that of the runestone somehow? Like with the pinkish-purple glow and the greyish-brown. You could turn the fire into a pink glow as well and It could look nice!

**Comment by FeignedIgnorance** [comment]
No longer for this pack
