### ISSUE TITLE
Dusty Runestone

### ISSUE THREAD

**Issue by resindrake** [FeignedIgnorance/StickyMC-Resource-Pack#14]

**Comment by FeignedIgnorance** [comment]
Please provide an image of one I have never seen a dusty runestone and need info to work with!

**Comment by resindrake** [comment]
Maybe just a greyed out version of the existing runestone texture?

**Comment by resindrake** [comment]
Here's what Google Images provides:
![image](https://user-images.githubusercontent.com/62374268/100382932-8aea1880-3070-11eb-889f-23dde414d906.png)

**Comment by FeignedIgnorance** [comment]
Ah I meant like the ingame dusty runestone item you get. Like is it also a prismarine shard?

**Comment by resindrake** [comment]
Ohh, it's just an enchanted flint. Turns into a random runestone when you rightclick.

**Comment by FeignedIgnorance** [comment]
Implemented!
