### ISSUE TITLE
[Overscoping!] "Generated" textures for non-mithril items

### ISSUE THREAD

**Issue by resindrake** [FeignedIgnorance/StickyMC-Resource-Pack#16]
If Optifine supports it, it'd be super easy to generate textures based on the name of the item.

All items have names consisting of two words, therefore in theory we could:
- Assign a base texture to the first word
- Assign an accent to the second word

**Comment by FeignedIgnorance** [comment]
This would be a huge endeavour to take on. It would take an incredibly long time to fully incorporate. Not only that but I feel having so many custom designs for legendaries would take away what makes mithril tools so special and unique. Also this idea sorta overlaps with the personalisation feature I want to try out later on in the line.

**Comment by resindrake** [comment]
Would you prefer me to keep overscoping/long term ideas out of the issues page?

**Comment by FeignedIgnorance** [comment]
I think for now that would be preferable yes. If we could keep the issues within the boundaries of specific items/sets as well as quick short term suggestions and such that would be great!
