### ISSUE TITLE
Kayran Set

### ISSUE THREAD

**Issue by FeignedIgnorance** [FeignedIgnorance/StickyMC-Resource-Pack#2]
* [x] Kayran Cleaver
* [x] Kayran Shears
* [x] Kayran Scythe
* [x] Kayran Shovel
* [ ] Kayran Crossbow
* [x] Kayran Blade
<img width="240" alt="Screen Shot 2020-11-17 at 2 53 04 pm" src="https://user-images.githubusercontent.com/74809955/99901351-42e29300-2d0a-11eb-80c7-d5557234639e.png">
<img width="260" alt="Screen Shot 2020-11-17 at 2 53 18 pm" src="https://user-images.githubusercontent.com/74809955/99901357-4e35be80-2d0a-11eb-9395-16065dec11be.png">
<img width="238" alt="Screen Shot 2020-11-17 at 2 53 30 pm" src="https://user-images.githubusercontent.com/74809955/99901361-5130af00-2d0a-11eb-9031-ad2a0e29c5c6.png">
<img width="269" alt="Screen Shot 2020-11-17 at 2 53 56 pm" src="https://user-images.githubusercontent.com/74809955/99901366-57bf2680-2d0a-11eb-970e-8bc268b5fc36.png">
<img width="274" alt="Screen Shot 2020-11-17 at 2 54 09 pm" src="https://user-images.githubusercontent.com/74809955/99901370-5beb4400-2d0a-11eb-9648-f8d274c23a74.png">
<img width="289" alt="Screen Shot 2020-11-17 at 2 54 24 pm" src="https://user-images.githubusercontent.com/74809955/99901372-60aff800-2d0a-11eb-9715-42c90634bd58.png">

**Comment by resindrake** [comment]
Promise I'll stop procrastinating today

**Comment by resindrake** [comment]
![image](https://user-images.githubusercontent.com/62374268/100043612-e5f9f080-2e61-11eb-8b2d-273fb7a71a19.png)
Help my terminal prompt is too long

**Comment by FeignedIgnorance** [comment]
Terminals hurt my brain

**Comment by FeignedIgnorance** [comment]
![dema](https://user-images.githubusercontent.com/74809955/100219424-17f67a00-2f6a-11eb-9851-f479d49aaed1.png)
![kay](https://user-images.githubusercontent.com/74809955/100219448-1d53c480-2f6a-11eb-801e-44fa2bb0c9ed.png)
![kay2](https://user-images.githubusercontent.com/74809955/100219570-483e1880-2f6a-11eb-9624-38b143fbf1e5.png)
I've done some little adjusting such as slight colour palette changes and a remodelling to fit the pre-set blade/ fit cleaver into item slot better. If you could use this palette when designing the other Kayran tools that would be great! Also please make sure to follow the basic shapes of the other tools with the same names such as "blade" and "chisel". You modelled the Kayran blade without the current Demagorgon's Blade template in mind so I assume there was a bit of confusion in the mix. I'm sorry about not clarifying that! We're releasing v0.5 once these Kayrans are done.
