### ISSUE TITLE
Update Forum Post

### ISSUE THREAD

**Issue by resindrake** [FeignedIgnorance/StickyMC-Resource-Pack#5]
Update [this forum post](https://stickymc.com/threads/stickymc-custom-texture-pack.2855/) to link to https://github.com/FeignedIgnorance/StickyMC-Resource-Pack/releases/latest

**Comment by resindrake** [comment]
Isn't this great? I can yell at you to do things without even being ingame!

**Comment by FeignedIgnorance** [comment]
Wow! Responsibilities! Link has been updated.
