### ISSUE TITLE
Codex Grimoire

### ISSUE THREAD

**Issue by resindrake** [FeignedIgnorance/StickyMC-Resource-Pack#9]
That annoying book we get too many of. It needs a texture so it doesn't look the same as enchanted books, duh

**Comment by resindrake** [comment]
![image](https://user-images.githubusercontent.com/62374268/100186513-44929d80-2f3a-11eb-94f6-8d04008166f8.png) ![image](https://user-images.githubusercontent.com/62374268/100186500-3f355300-2f3a-11eb-9e4b-872dfc67e9c0.png)

**Comment by resindrake** [comment]
Reopening because the metadata is still missing

**Comment by FeignedIgnorance** [comment]
Metadata has now been added
